# Generated by Django 4.1.7 on 2023-02-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Soma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num1", models.IntegerField()),
                ("num2", models.IntegerField()),
                ("resultado", models.IntegerField()),
                ("data", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
